language: node_js
node_js:
  - "10"
cache:
  npm: false
sudo: required
dist: trusty

#Install headless Chrome
addons:
  chrome: stable

cache:
  directories:
    - node_modules

branches:
  only:
  - master

script:
  - npm test
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_success:
  - npm run coveralls
