dist: xenial
sudo: required

language: node_js
node_js:
  - "10"

#Install headless Chrome
addons:
  chrome: stable

cache:
  npm: false

branches:
  only:
  - master

script:
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

after_success:
  - npm run coveralls
