name: PROD delivery

on:
  push:
    branches: [ master ]
env:
  AZURE_WEBAPP_NAME: nebular2
  AZURE_WEBAPP_PACKAGE_PATH: './dist'
  NODE_VERSION: '16.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install

    - name: Unit tests
      run: npm run test

    - name: Upload statistics to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update Chrome before E2E
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version

    - name: TEST of E2E tests
      run: npm run e2e-auto

    - name: E2E tests on Chrome
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        start: npm start
        wait-on: 'http://localhost:4200'

    - name: E2E tests
      uses: cypress-io/github-action@v5
      with:
        start: npm start
        wait-on: 'http://localhost:4200'

    - name: PROD build
      run: npm run build

    - name: 'Deploy to Azure webapp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.NEBULAR_WEBAPPPUBLISHPROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
