name: Build and deploy to Azure web app NEBULAR

on:
  push:
    branches: [ master ]
env:
  AZURE_WEBAPP_NAME: nebular2
  AZURE_WEBAPP_PACKAGE_PATH: './dist'
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build -- --prod
       
    - name: 'Deploy to Azure webapp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.NEBULAR_WEBAPPPUBLISHPROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
